// GENERATED by tools/make-base-pack.ts — do not edit; run `bun tools/make-base-pack.ts`.
// SHA-256 of src/packs/base-pack.json (first 12 hex), the bundled base
// content's identity in replay meta (see RunConfig.contentFingerprint in
// src/game/run.ts). tools/make-base-pack.test.ts byte-diffs it against the
// generator, so it cannot silently disagree with the JSON it fingerprints.
export const CONTENT_FINGERPRINT = 'ce6616c9f08e';
