// GENERATED by tools/make-v4-content.ts — do not edit; run `bun tools/make-v4-content.ts`.
// SHA-256 of src/v4/content/campaign.json (first 12 hex), the bundled v4
// content's identity in replay meta (see RunConfig.contentFingerprint in
// src/game/run.ts). tools/make-v4-content.test.ts byte-diffs it against the
// generator, so it cannot silently disagree with the JSON it fingerprints.
export const CONTENT_FINGERPRINT = 'a0f4455ce9d8';
